spring.cloud.stream:
  function:
    definition: domainService
  bindings:
    domainService-in-0:
      destination: MESSAGE-TOPIC
  kafka:
    bindings:
      domainService-in-0:
        consumer:
          configuration:
            value:
              deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    binder:
      brokers:
          - localhost:9092